name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.2.4
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  dio: ^5.3.2
  flutter_local_notifications: ^15.1.1
  rxdart: ^0.27.7

  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  package_info_plus: ^4.1.0
  # open_file: ^3.2.1
  sensors_plus: ^3.0.3
  share_plus: ^7.1.0
  chopper: ^4.0.1
  collection: ^1.17.1

dev_dependencies:
  flutter_lints: ^3.0.2
